function titleString = titleSheet()
titleString = {
'                                                                         '
'                                                                         '
'                  $ $ $                                                  '
'         $ $ $ $ $ $ $ $ $ $ $                                           '
'    $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $                                    '
'             $ $ $ $ $ $ $ $ $ $ $ $ $ $                                 '
'                      $ $ $ $ $ $ $ $ $                                  '
'                          $ $ $ $ $ $ $ $                                '
'                               $ $ $ $ $ $                               '
'                                   $ $ $ $                               '
'                                   $ $ $                                 '
'                                 $ $ $                                   '
'                    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
'                    $$                           $$'
'              $$$$$$$$     NASTRAN Compatible    $$'
'             $$     $$   Finite Elements (CoFE)  $$'
'            $$      $$                           $$'
'             $$     $$   Designed in 2013-2015   $$'
'              $$    $$    by Anthony Ricciardi   $$'
'               $$   $$       pasquale@vt.edu     $$'
'                $$  $$  NastranCoFE.weebly.com   $$'
'                 $$$$$                           $$'
'                    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
''
''
'---------------------------------------------------------------------------'
'  The MIT License (MIT)'
''
'  Copyright (c) 2015 Anthony Ricciardi <pasquale@vt.edu>'
''
'  Permission is hereby granted, free of charge, to any person obtaining a copy'
'  of this software and associated documentation files (the "Software"), to deal'
'  in the Software without restriction, including without limitation the rights'
'  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell'
'  copies of the Software, and to permit persons to whom the Software is'
'  furnished to do so, subject to the following conditions:'
''
'  The above copyright notice and this permission notice shall be included in all'
'  copies or substantial portions of the Software.'
''
'  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR'
'  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,'
'  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE'
'  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER'
'  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,'
'  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE'
'  SOFTWARE.'
''
'---------------------------------------------------------------------------'
''
'  NASTRAN is a registered trademark of the National Aeronautics and Space '
'  Administration.  '
''
'  MSC Nastran is a registered trademark of MSC Software Corporation.      '
''
'---------------------------------------------------------------------------'
''
'  KNOWN DIFFERENCE FROM MSC Nastran:'
'  MSC Nastran CBEAM element force output for BENDING MOMENT - PLANE 2 '
'  uses an opposite sign convention than the convention used in CoFE. All'
'  other element force outputs are consistent with MSC Nastran.'
''
'  FORMAT'
'  Node and element numbers are output as ordered in the input file.'
''
'---------------------------------------------------------------------------'
};
 
