function [obj,obj_prime] = differential(obj,obj_prime)

obj.kd = obj.force(7)*obj.kdp + ...
         obj.force(8)*obj.kdvy + ...
         obj.force(9)*obj.kdvz  + ...
         obj.force(10)*obj.kdmx + ...
         obj.force(11)*obj.kdmy2 + ...
         obj.force(12)*obj.kdmz2;

if nargin > 1
    obj_prime.kd = obj_prime.force(7)*obj.kdp + ...
         obj_prime.force(8)*obj.kdvy + ...
         obj_prime.force(9)*obj.kdvz  + ...
         obj_prime.force(10)*obj.kdmx + ...
         obj_prime.force(11)*obj.kdmy2 + ...
         obj_prime.force(12)*obj.kdmz2 + ...
         obj.force(7)*d(obj_prime.kdp) + ...
         obj.force(8)*d(obj_prime.kdvy) + ...
         obj.force(9)*d(obj_prime.kdvz)  + ...
         obj.force(10)*d(obj_prime.kdmx) + ...
         obj.force(11)*d(obj_prime.kdmy2) + ...
         obj.force(12)*d(obj_prime.kdmz2);
end
end