function plot(obj,gnum,gnum2gdof,allDef,varargin)

x = [obj.x1,obj.x2,obj.x3,obj.x4,obj.x1];
if isempty(allDef);
    def = zeros(3,4);
else
    def = allDef(gnum2gdof(1:3,[find(gnum==obj.G1),find(gnum==obj.G2),find(gnum==obj.G3),find(gnum==obj.G4)]));
end

% perimeter
p = x + [def,def(:,1)];
plot3(p(1,:),p(2,:),p(3,:),varargin{:})

% position/deformation contour
% [xip,etap] = meshgrid(linspace(-1,1,10),linspace(-1,1,10));
% if any(strcmp(varargin,'contour'))
%     x1 =x(1,1)*obj.N(1,xip,etap) + ...
%         x(1,2)*obj.N(2,xip,etap) + ...
%         x(1,3)*obj.N(3,xip,etap) + ...
%         x(1,4)*obj.N(4,xip,etap);
%     x2 =x(2,1)*obj.N(1,xip,etap) + ...
%         x(2,2)*obj.N(2,xip,etap) + ...
%         x(2,3)*obj.N(3,xip,etap) + ...
%         x(2,4)*obj.N(4,xip,etap);
%     x3 =x(3,1)*obj.N(1,xip,etap) + ...
%         x(3,2)*obj.N(2,xip,etap) + ...
%         x(3,3)*obj.N(3,xip,etap) + ...
%         x(3,4)*obj.N(4,xip,etap);
%     
%     d1 =def(1,1)*obj.N(1,xip,etap) + ...
%         def(1,2)*obj.N(2,xip,etap) + ...
%         def(1,3)*obj.N(3,xip,etap) + ...
%         def(1,4)*obj.N(4,xip,etap);
%     d2 =def(2,1)*obj.N(1,xip,etap) + ...
%         def(2,2)*obj.N(2,xip,etap) + ...
%         def(2,3)*obj.N(3,xip,etap) + ...
%         def(2,4)*obj.N(4,xip,etap);
%     d3 =def(3,1)*obj.N(1,xip,etap) + ...
%         def(3,2)*obj.N(2,xip,etap) + ...
%         def(3,3)*obj.N(3,xip,etap) + ...
%         def(3,4)*obj.N(4,xip,etap);
% 
%     surf(x1+d1,x2+d2,x3+d3,sqrt(d1.^2+d2.^2+d3.^2),'facecolor','interp','edgecolor','none');
end